name: Documentation
description: Report issues or suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Incorrect or outdated information
        - Missing documentation
        - Unclear or confusing explanation
        - Typo or formatting issue
        - Code example doesn't work
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Which file or section is this about?
      placeholder: "README.md, PUBLISHING.md, etc."
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: The README says to run 'npm install' but this project uses 'bun install'...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be changed or improved?
      placeholder: The README should be updated to show 'bun install' instead...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples here.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have identified the specific documentation that needs updating
          required: true
